title: Shariq Iqbal
description: PhD student at USC Computer Science. Researching Machine Learning.

baseurl:  # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://shariqiqbal2810.github.io" # change this to the base hostname & protocol for your site

google_analytics:
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

author: "Shariq Iqbal"

social:
  github_username:  shariqiqbal2810
  linkedin_username:  shariqiqbal2810
  soundcloud: sharqq
  spotify: 1251124013
  twitter_username: shariqbal
  google_scholar_page: https://scholar.google.com/citations?user=pRb9yXEAAAAJ&hl=en

markdown: kramdown

